language: python

sudo: false

before-install:
- python3 -m venv venv/

install:
- source venv/bin/activate
- pip install -r requirements.txt
- pip install mypy

script:
- source venv/bin/activate
- ./mypyall.py
